### ISSUE TITLE
Authentication problems with Keystone when creating two ClientHttp

### ISSUE THREAD

**Issue by yuw726** [gwdg/rOCCI-api#38]
Hello!

I was testing code with two clients like this:

```
@rocci_client = Occi::Api::Client::ClientHttp.new({
          :endpoint => "http://<occi_server_ip>:8787/",
          :auth => {
            :type       => "basic",
            :username   => "**********************",
            :password   => "**********************"
          },
          :log => {
            :out        => STDOUT,
            :level      => Occi::Api::Log::ERROR
          }
        })


@second_client = Occi::Api::Client::ClientHttp.new({
          :endpoint => "http://<occi_server_ip>:8787/",
          :auth => {
            :type       => "basic",
            :username   => "**********************",
            :password   => "**********************"
          },
          :log => {
            :out        => STDOUT,            
            :level      => Occi::Api::Log::ERROR
          }      
        })
```

, but got this error: Keystone AuthN failed with 405! (Method not allowed)

I noticed a comment "# OCCI-OS doesn't support HEAD method!" in keystone.rb, but set_keystone_base_url function still uses @env_ref.class.head.

When I changed this to "get", another problem was that second client was trying to get his own token, but all requests were sent with "X-Auth-Token"=>"{token_of_first_client}".

My solution is to modify keystone.rb in this way:

```
def set_keystone_base_url
          if !@env_ref.class.headers['X-Auth-Token'].blank?
            @env_ref.class.headers.clear
          end

          response = @env_ref.class.get "#{@env_ref.endpoint.to_s}/-/"
```

I didn't make pull request because I'm not sure if this is a correct way to solve this problem. But at least my script is working OK with these modifications

**Comment by arax** [comment]
Hello @yuw726 

ad. HTTP `HEAD`, good point. I will investigate why this works on our production infrastructure and modify the code to be more accommodating.

ad. two clients, again a good point. There is a design flaw in the client. I will do my best to fix it ASAP or at least to give you a monkey patch to use. The problem is caused by `@env_ref.class` referring to the same class on both clients ... therefore the second client with change the first client's token and the other way around.

**Comment by yuw726** [comment]
Small note: error 405 appears only when creating second client. First one is created and works without any problem -> HEAD method works fine for one instance, but fails for second.

**Comment by arax** [comment]
I suspect this is related to the `@env_ref.class` issue. The second client (unintentionally) shares auth information with the first client, therefore the `HEAD` request is passed (as an already authenticated request) to the underlying OCCI server instead of being processed by the authentication/authorization middleware. The OCCI server does not support `HEAD` requests, the middleware does.

**Comment by arax** [comment]
This is not something I can easily fix in this version of the client. If you need to use it, I can offer you a quick hack fixing the most critical parts of the problem. I'm already planning a re-write that will replace some of the internally used libraries and improves the code quality. I will add this to the ToDo list, with the highest priority.

**Comment by yuw726** [comment]
Seems like workaround from my first post works for my case, so for now it is enough. Will be waiting for next update :)

**Comment by arax** [comment]
Ok. Please, be careful, in that setup the second client instance can influence the environment of the first client instance.
